apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-00-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Autoever-Cloud/argocd-kafka-cluster-manifests.git"
    targetRevision: HEAD
    path: base/00-core
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 