apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-00-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Autoever-Cloud/argocd-kafka-cluster-manifests.git"
    targetRevision: HEAD
    path: base/00-core
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bfdprofiles.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgpadvertisements.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle